"""Export a trained PyTorch RedTeam policy as a standalone synchronous JS bot."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import torch


EXPECTED_SHAPES = {
    "body.0.weight": (64, 92),
    "body.0.bias": (64,),
    "body.2.weight": (64, 64),
    "body.2.bias": (64,),
    "policy.weight": (18, 64),
    "policy.bias": (18,),
}


def js_array(tensor: torch.Tensor) -> str:
    values = tensor.detach().cpu().to(torch.float32).contiguous().view(-1).tolist()
    return json.dumps(values, separators=(",", ":"), allow_nan=False)


def export_policy(checkpoint_path: Path, output_path: Path) -> dict:
    raw = checkpoint_path.read_bytes()
    checkpoint_sha256 = hashlib.sha256(raw).hexdigest()
    saved = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    state = saved["model"]
    for key, shape in EXPECTED_SHAPES.items():
        if key not in state:
            raise KeyError(f"checkpoint is missing {key}")
        actual = tuple(state[key].shape)
        if actual != shape:
            raise ValueError(f"{key}: expected {shape}, got {actual}")

    config = saved.get("config", {})
    winning_score = int(config.get("winning_score", 10))
    metadata = {
        "format": 1,
        "checkpoint": checkpoint_path.name,
        "checkpointSha256": checkpoint_sha256,
        "globalStep": int(saved.get("global_step", 0)),
        "trainingSeed": int(config.get("seed", 0)),
        "winningScore": winning_score,
        "observationSize": 92,
        "frameStack": 4,
        "featuresPerFrame": 23,
        "actionCount": 18,
        "architecture": "92-tanh64-tanh64-18",
    }
    meta_json = json.dumps(metadata, ensure_ascii=False, separators=(",", ":"))

    source = f"""'use strict';
/* eslint-disable no-loss-of-precision -- exact float32 checkpoint literals */
/* ========================================================================== 
 * RedTeam_RL_v1 — deterministic PPO policy exported from {checkpoint_path.name}
 * Checkpoint SHA-256: {checkpoint_sha256}
 * Generated by bot-dev/rl/export_policy.py. Do not hand-edit the weights.
 * ========================================================================== */

var RL_META = {meta_json};
var RL_W1 = new Float32Array({js_array(state['body.0.weight'])});
var RL_B1 = new Float32Array({js_array(state['body.0.bias'])});
var RL_W2 = new Float32Array({js_array(state['body.2.weight'])});
var RL_B2 = new Float32Array({js_array(state['body.2.bias'])});
var RL_WP = new Float32Array({js_array(state['policy.weight'])});
var RL_BP = new Float32Array({js_array(state['policy.bias'])});
var RL_ACTIONS = (function () {{
  var actions = [];
  for (var x = -1; x <= 1; x++) {{
    for (var y = -1; y <= 1; y++) {{
      for (var hit = 0; hit <= 1; hit++) actions.push({{ x: x, y: y, hit: hit }});
    }}
  }}
  return actions;
}})();

var RL = {{
  frames: [],
  lastAction: {{ x: 0, y: 0, hit: 0 }},
  lastScoreTotal: null,
  lastTick: null,
  side: null,
  lastObservation: null,
  lastLogits: null,
  lastActionIndex: 0
}};

function rlClamp(value, lo, hi) {{
  return value < lo ? lo : (value > hi ? hi : value);
}}

function rlReset(appliedAction) {{
  var action = appliedAction || {{ x: 0, y: 0, hit: 0 }};
  RL.frames = [];
  RL.lastAction = {{ x: action.x | 0, y: action.y | 0, hit: action.hit ? 1 : 0 }};
  RL.lastScoreTotal = null;
  RL.lastTick = null;
  RL.side = null;
  RL.lastObservation = null;
  RL.lastLogits = null;
  RL.lastActionIndex = 0;
}}

function rlEncodeFrame(snapshot, appliedAction) {{
  var right = snapshot.side === 'RIGHT';
  var self = snapshot.self;
  var opp = snapshot.opp;
  var ball = snapshot.ball;
  var meta = snapshot.meta;
  var score = meta.score;
  var action = appliedAction || {{ x: 0, y: 0, hit: 0 }};
  var bx = right ? 432 - ball.x : ball.x;
  var bvx = right ? -ball.xVelocity : ball.xVelocity;
  var landingX = right ? 432 - ball.expectedLandingPointX : ball.expectedLandingPointX;
  var selfX = right ? 432 - self.x : self.x;
  var oppX = right ? 432 - opp.x : opp.x;
  var selfDive = right ? -self.divingDirection : self.divingDirection;
  var oppDive = right ? -opp.divingDirection : opp.divingDirection;
  var selfServe = right ? meta.isPlayer2Serve : !meta.isPlayer2Serve;
  return new Float32Array([
    bx / 216 - 1,
    rlClamp(ball.y / 252, -0.25, 1.25),
    rlClamp(bvx / 40, -1.5, 1.5),
    rlClamp(ball.yVelocity / 40, -1.5, 1.5),
    landingX / 216 - 1,
    ball.isPowerHit ? 1 : 0,
    selfX / 216 - 1,
    rlClamp(self.y / 244, 0, 1.25),
    rlClamp(self.state / 4, 0, 1),
    rlClamp(self.frameNumber / 5, 0, 1),
    rlClamp(selfDive, -1, 1),
    oppX / 216 - 1,
    rlClamp(opp.y / 244, 0, 1.25),
    rlClamp(opp.state / 4, 0, 1),
    rlClamp(opp.frameNumber / 5, 0, 1),
    rlClamp(oppDive, -1, 1),
    rlClamp(score.self / {winning_score}, 0, 1),
    rlClamp(score.opp / {winning_score}, 0, 1),
    selfServe ? 1 : 0,
    rlClamp(meta.rallyFrameCount / 300, 0, 2),
    action.x,
    action.y,
    action.hit
  ]);
}}

function rlObserve(snapshot) {{
  var score = snapshot.meta.score;
  var scoreTotal = (score.self || 0) + (score.opp || 0);
  var reset = RL.frames.length === 0 ||
    RL.side !== snapshot.side ||
    (RL.lastTick !== null && snapshot.tick < RL.lastTick) ||
    (RL.lastScoreTotal !== null && scoreTotal < RL.lastScoreTotal);
  var frame = rlEncodeFrame(snapshot, RL.lastAction);
  if (reset) {{
    RL.frames = [frame.slice(), frame.slice(), frame.slice(), frame.slice()];
  }} else {{
    RL.frames.push(frame);
    while (RL.frames.length > 4) RL.frames.shift();
  }}
  var observation = new Float32Array(92);
  for (var i = 0; i < 4; i++) observation.set(RL.frames[i], i * 23);
  RL.lastObservation = observation;
  RL.lastScoreTotal = scoreTotal;
  RL.lastTick = snapshot.tick;
  RL.side = snapshot.side;
  return observation;
}}

function rlDenseTanh(input, weights, bias, outputSize, inputSize) {{
  var output = new Float32Array(outputSize);
  for (var o = 0; o < outputSize; o++) {{
    var sum = bias[o];
    var offset = o * inputSize;
    for (var i = 0; i < inputSize; i++) sum += input[i] * weights[offset + i];
    output[o] = Math.tanh(sum);
  }}
  return output;
}}

function rlPolicyLogits(observation) {{
  var h1 = rlDenseTanh(observation, RL_W1, RL_B1, 64, 92);
  var h2 = rlDenseTanh(h1, RL_W2, RL_B2, 64, 64);
  var logits = new Float32Array(18);
  for (var o = 0; o < 18; o++) {{
    var sum = RL_BP[o];
    var offset = o * 64;
    for (var i = 0; i < 64; i++) sum += h2[i] * RL_WP[offset + i];
    logits[o] = sum;
  }}
  return logits;
}}

function rlArgmax(logits) {{
  var best = 0;
  for (var i = 1; i < logits.length; i++) if (logits[i] > logits[best]) best = i;
  return best;
}}

function decide(snapshot) {{
  var observation = rlObserve(snapshot);
  var logits = rlPolicyLogits(observation);
  var index = rlArgmax(logits);
  var selected = RL_ACTIONS[index];
  var action = {{ x: selected.x, y: selected.y, hit: selected.hit }};
  RL.lastLogits = logits;
  RL.lastActionIndex = index;
  /* Preserve the raw action exactly as the training environment did. */
  RL.lastAction = {{ x: action.x, y: action.y, hit: action.hit }};
  return action;
}}

decide.__rl = {{
  metadata: RL_META,
  reset: rlReset,
  encodeFrame: rlEncodeFrame,
  policyLogits: rlPolicyLogits,
  inferActionIndex: function (observation) {{ return rlArgmax(rlPolicyLogits(observation)); }},
  lastObservation: function () {{ return RL.lastObservation; }},
  lastLogits: function () {{ return RL.lastLogits; }},
  lastActionIndex: function () {{ return RL.lastActionIndex; }}
}};
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(source, encoding="utf-8", newline="\n")
    return metadata


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("checkpoint", type=Path)
    parser.add_argument("output", type=Path)
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    result = export_policy(args.checkpoint.resolve(), args.output.resolve())
    print(json.dumps({"output": str(args.output.resolve()), **result}, indent=2))
